#!/usr/bin/env python
# Creating a list of AWS services and populating it into an empty list
# Create an empty list to store AWS services
aws_services = []
print(awsservices)

# Add some AWS services to the list
aws-services.append("EC2")
aws-services.append("S3")
aws-services.append("Cloud9")
aws-services.append("DynamoDB")
aws-services.append("AWS Lambda")
aws-services.append("ECS")
aws-services.append("RDS")
aws-services.append("VPC")

# Print the list and the length of the list
print("aws-services")
print("The lenght of the list is", len(aws-services)

# Remove two specific services from the list
aws-services.remove("EC2")
aws-services.remove("RDS")

# Print the new list and its length
print("Updated AWS Services: ", aws-services)
print("New Length: ", len(aws-services))
